### ISSUE TITLE
Error with time data

### ISSUE THREAD

**Issue by petzi53** [thomasf/exitwp#70]
When I run `python exitwp.py` I got the following error message:

`Traceback (most recent call last):
  File "exitwp.py", line 374, in <module>
    write_jekyll(data, target_format)
  File "exitwp.py", line 296, in write_jekyll
    i['date'], '%Y-%m-%d %H:%M:%S').replace(tzinfo=UTC()),
  File "/Users/petzi/.pyenv/versions/2.7.10/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '0000-00-00 00:00:00' does not match format '%Y-%m-%d %H:%M:%S'`

I am no Python programmer but I looked up what the time data format means and it seems to me that '0000-00-00 00:00:00' DOES MATCH the format '%Y-%m-%d %H:%M:%S'.

Any idea what is wrong? Help would be **very** appreciated!

**Comment by petzi53** [comment]
This issue is solved: I've got an [answer for my question at StackOverflow](https://stackoverflow.com/questions/45905739/valueerror-time-data-0000-00-00-000000-does-not-match-format-y-m-d-h/45905782#45905782).
