### ISSUE TITLE
Migrating to python 3

### ISSUE THREAD

**Issue by AForteCellenza** [thomasf/exitwp#76]
Hi,

I'm trying to make a python 3 version of this module. But i got a little problem replacing XMLtreeBuilder by XMLParser in this class:

`class ns_tracker_tree_builder(XMLParser):

    def __init__(self):
        XMLParser.__init__(self)
        self._parser.StartNamespaceDeclHandler = self._start_ns
        self.namespaces = {}

    def _start_ns(self, prefix, ns):
        self.namespaces[prefix] = '{' + ns + '}'`

I get this error:

Traceback (most recent call last):
  File "exitwp.py", line 374, in <module>
    data = parse_wp_xml(wpe)
  File "exitwp.py", line 83, in parse_wp_xml
    parser = ns_tracker_tree_builder()
  File "exitwp.py", line 65, in __init__
    self._parser.StartNamespaceDeclHandler = self._start_ns
AttributeError: 'ns_tracker_tree_builder' object has no attribute '_parser'

regards,

**Comment by omajid** [comment]
I have a PR with the fix (for a hugo-based fork though), here: https://github.com/wooni005/exitwp-for-hugo/pull/4/files#diff-07a925cb3868c2d0586bbc2bba16a16dR64
